### ISSUE TITLE
Page de détails d'un produit.

### ISSUE THREAD

**Issue by BlackPowerC** [thiernoalhassane/eshopweb#14]
L'ajout d'un commentaire déforme la page.

**Comment by thiernoalhassane** [comment]
comment ca

**Comment by BlackPowerC** [comment]
la page est normale. Je fait un commentaire et là, la colonne de l'image se décale vers le bas et le
formulaire d'ajout du commenataire vers la droit.

**Comment by BlackPowerC** [comment]
c'est réglé. pull request.
